services:
  mongodb:
    image: mongo:8
    container_name: ohe-track-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ohe_mongo_data:/data/db
volumes:
  ohe_mongo_data:
